module.exports = {
	FORBIDDEN: "You are forbidden to complete this attempt.",
	FOUND_USER: "Username has been used. Please try another.",
	INVALID_DOB: "Invalid date of birth.",
	INVALID_EMAIL: "Invalid email.",
	INVALID_IMAGE: "Invalid image.",
	INVALID_INPUT: "Invalid input.",
	INVALID_PHONENUMBER: "Invalid phone number.",
	INVALID_PHOTOURL: "Invalid photo url.",
	INVALID_TOKEN: "Expired or invalid token.",
	LOGIN_REQUIRED: "Please login to continue.",
	MISSING_AUTH_INPUT: "Please provide both username and password.",
	MISSING_IMAGE_INPUT: "Please provide image data.",
	MISSING_NEWS_INPUT: "Please provide all required fields for news.",
	MISSING_PRODUCT_INPUT: "Please provide all required fields for product",
	MISSING_USER_INPUT: "Please provide all required fields for user.",
	NOT_FOUND_NEWS: "News does not exist.",
	NOT_FOUND_PRODUCT: "Product does not exist.",
	NOT_FOUND_USER: "User does not exist.",
	SYSTEM_ERROR: "System error. Please contact us for support.",
	UNDEFINED_ROUTE: "Undefined route.",
	WRONG_AUTH_INPUT: "Incorrect email or password."
}
