module.exports = {
	FORBIDDEN: "Yêu cầu quyền truy cập để thực hiện hành động này.",
	FOUND_USER: "Tên đăng nhập đã được sử dụng.",
	INVALID_DOB: "Ngày sinh không hợp lệ.",
	INVALID_EMAIL: "Email không hợp lệ.",
	INVALID_IMAGE: "Ảnh không hợp lệ.",
	INVALID_INPUT: "Dữ liệu đầu vào không hợp lệ.",
	INVALID_PHONENUMBER: "Số điện thoại di động không hợp lệ.",
	INVALID_PHOTOURL: "URL của ảnh không hợp lệ.",
	INVALID_TOKEN: "Token đã hết hạn hoặc không hợp lệ.",
	LOGIN_REQUIRED: "Vui lòng đăng nhập để tiếp tục.",
	MISSING_AUTH_INPUT: "Vui lòng nhập tên đăng nhập và mật khẩu.",
	MISSING_IMAGE_INPUT: "Vui lòng cung cấp dữ liệu ảnh.",
	MISSING_NEWS_INPUT: "Vui lòng nhập đủ các thông tin bắt buộc cho bài viết.",
	MISSING_USER_INPUT: "Vui lòng cung cấp dữ liệu người dùng.",
	NOT_FOUND_NEWS: "Bản tin không tồn tại",
	NOT_FOUND_USER: "Người dùng không tồn tại.",
	SYSTEM_ERROR: "Hệ thống xảy ra sự cố. vui lòng liên hệ với chúng tôi để được tư vấn.",
	UNDEFINED_ROUTE: "Route không tồn tại.",
	WRONG_AUTH_INPUT: "Tên đăng nhập hoặc mật khẩu không đúng."
}
