module.exports = {
    CART_ITEM_EXIST: "This item is already in your cart.",
    FORBIDDEN: "You are forbidden to complete this attempt.",
    FOUND_USER: "Username has been used. Please try another.",
	INCORRECT_PASSWORD: "Incorrect password.",
    INVALID_CART_ITEM_QUANTITY: "Invalid item quantity.",
    INVALID_DOB: "Invalid date of birth.",
    INVALID_EMAIL: "Invalid email.",
    INVALID_IMAGE: "Invalid image.",
    INVALID_INPUT: "Invalid input.",
    INVALID_INVOICE_PRODUCTS: "Your invoice has at least 1 invalid item in product list.",
    INVALID_PHONENUMBER: "Invalid phone number.",
    INVALID_PHOTOURL: "Invalid photo url.",
    INVALID_TOKEN: "Expired or invalid token.",
    LOGIN_REQUIRED: "Please login to continue.",
    MISSING_AUTH_INPUT: "Please provide both username and password.",
    MISSING_CART_ITEM_ID: "Please provide item _id.",
    MISSING_CART_ITEM_QUANTITY: "Please provide item quantity.",
    MISSING_IMAGE_INPUT: "Please provide image data.",
    MISSING_INVOICE_PRODUCTS: "Please provide a product list.",
    MISSING_INVOICE_ID: "Please provide invoice id",
    MISSING_OLD_PASSWORD: "Please provide your current password.",
    MISSING_NEWS_INPUT: "Please provide all required fields for news.",
    MISSING_PAYMENT_METHOD: "Please provide payment method.",
    MISSING_PRODUCT_INPUT: "Please provide all required fields for product",
    MISSING_USER_INPUT: "Please provide all required fields for user.",
    NOT_FOUND_CART: "This account does not own any cart.",
    NOT_FOUND_INVOICE: "This invoice does not exist.",
    NOT_FOUND_NEWS: "This news does not exist.",
    NOT_FOUND_PRODUCT: "This product does not exist.",
    NOT_FOUND_PRODUCT_IN_CART: "A product does not exist in your cart.",
    NOT_FOUND_USER: "This account does not exist.",
    SYSTEM_ERROR: "System error. Please contact us for support.",
    UNDEFINED_ROUTE: "Undefined route.",
    UNKNOWN_PAYMENT_METHOD: "Unknown payment method.",
    WRONG_AUTH_INPUT: "Incorrect email or password."
};
